#!/usr/bin/env python
"""Regenerate the body of the website's schema.html and routes.html from the code.

Run from the edgecase repo root with the venv python:
    venv/bin/python tools/gen_site_reference.py /path/to/edgecase-website/docs

Keeps each page's chrome (everything outside <article class="doc-content">)
and rebuilds the article from the live schema and Flask url_map, so the
reference pages cannot drift from the code between releases.
"""
import html
import os
import re
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

TABLE_PURPOSE = {
    'clients': 'Client records',
    'client_types': 'Status categories (Active, Inactive, custom)',
    'entries': 'Unified entry storage (the core)',
    'link_groups': 'Couples / family / group therapy',
    'client_links': 'Link group membership with per-member fees',
    'entry_links': 'Links between entries across clients',
    'attachments': 'Encrypted file uploads',
    'expense_categories': 'User-defined expense categories',
    'payees': 'Expense payee names (autocomplete)',
    'income_payors': 'Income payor names (autocomplete)',
    'settings': 'Application configuration',
    'archived_clients': 'Minimal record kept after retention deletion',
    'statement_portions': 'Per-payer statement balances and status',
    'payment_allocations': 'Which statements each payment settled; NULL portion = credit',
}

BP_PURPOSE = {
    'auth': 'Login, first run, recovery key, disaster recovery',
    'clients': 'Client list, client file, profile, retention',
    'entries': 'Session, communication, absence, item, upload forms; redaction; edit history',
    'statements': 'Unbilled search, generation, sending, payments, write-offs',
    'ledger': 'Income, expenses, financial and payment-record reports',
    'links': 'Link groups',
    'types': 'Client types',
    'backups': 'Backup, restore, retention settings',
    'scheduler': 'Calendar events',
    'settings': 'Practice settings, security, AI model management',
    'ai': 'AI Scribe',
    'app': 'Session keepalive and status endpoints registered on the app itself, not a blueprint',
}


def schema_sql():
    src = (ROOT / 'core' / 'database.py').read_text()
    out = []
    for m in re.finditer(r'CREATE TABLE IF NOT EXISTS (\w+) \((.*?)\n\s*\)', src, re.S):
        name, body = m.group(1), m.group(2)
        lines = [ln.strip() for ln in body.strip().splitlines()]
        lines = [ln for ln in lines if ln and not ln.startswith('--')]
        out.append((name, 'CREATE TABLE %s (\n    %s\n);' % (name, '\n    '.join(lines))))
    return out


def routes():
    os.environ.setdefault('EDGECASE_DATA', tempfile.mkdtemp(prefix='ec-routes-'))
    os.environ.setdefault('EDGECASE_FAST_KDF', '1')
    from web.app import app
    rules = [r for r in app.url_map.iter_rules() if r.endpoint != 'static']
    by_bp = {}
    for r in rules:
        bp = r.endpoint.split('.')[0] if '.' in r.endpoint else 'app'
        methods = sorted(m for m in r.methods if m not in ('HEAD', 'OPTIONS'))
        by_bp.setdefault(bp, []).append((r.rule, ', '.join(methods), r.endpoint.split('.')[-1]))
    for bp in by_bp:
        by_bp[bp].sort()
    return by_bp, len(rules)


def replace_article(path, article_html):
    s = Path(path).read_text()
    a = s.index('<article class="doc-content">')
    b = s.index('</article>', a) + len('</article>')
    Path(path).write_text(s[:a] + article_html + s[b:])


def build_schema(tables):
    rows = '\n'.join(
        '                        <tr><td>%s</td><td>%s</td></tr>' % (n, html.escape(TABLE_PURPOSE.get(n, '')))
        for n, _ in tables)
    sections = '\n'.join('''            <section class="doc-section">
                <h2>%s</h2>
                <p>%s.</p>
                <pre><code>%s</code></pre>
            </section>''' % (n, html.escape(TABLE_PURPOSE.get(n, '')), html.escape(sql)) for n, sql in tables)
    return '''<article class="doc-content">
            <section class="doc-section">
                <h2>Overview</h2>
                <p>EdgeCase uses SQLite with SQLCipher encryption. The database contains %d tables organized around an entry-based architecture where all client records are stored as unified entries. The definitions below are read from <code>core/database.py</code> at the tagged release; this page is regenerated by <code>tools/gen_site_reference.py</code>.</p>
                <p>Database location: <code>data/edgecase.db</code> under the EdgeCase data folder.</p>
            </section>

            <section class="doc-section">
                <h2>Tables at a Glance</h2>
                <table class="schema-table">
                    <thead>
                        <tr>
                            <th>Table</th>
                            <th>Purpose</th>
                        </tr>
                    </thead>
                    <tbody>
%s
                    </tbody>
                </table>
            </section>

%s
        </article>''' % (len(tables), rows, sections)


def build_routes(by_bp, total):
    order = [b for b in BP_PURPOSE if b in by_bp] + sorted(b for b in by_bp if b not in BP_PURPOSE)
    sections = []
    for bp in order:
        rows = '\n'.join('                        <tr><td><code>%s</code></td><td>%s</td><td><code>%s</code></td></tr>'
                         % (html.escape(rule), methods, fn) for rule, methods, fn in by_bp[bp])
        sections.append('''            <section class="doc-section">
                <h2>%s</h2>
                <p>%s. %d routes.</p>
                <table class="schema-table">
                    <thead><tr><th>Route</th><th>Methods</th><th>Handler</th></tr></thead>
                    <tbody>
%s
                    </tbody>
                </table>
            </section>''' % (bp + '_bp' if bp != 'app' else 'app (no blueprint)', html.escape(BP_PURPOSE.get(bp, '')), len(by_bp[bp]), rows))
    return '''<article class="doc-content">
            <section class="doc-section">
                <h2>Overview</h2>
                <p>%d routes across %d blueprints (plus four app-level session-keepalive endpoints, listed last), read from the Flask url map at the tagged release; this page is regenerated by <code>tools/gen_site_reference.py</code>. Routes under <code>/restore</code> and <code>/recover</code> are reachable without login by design &mdash; see <a href="backups.html">Backups</a>.</p>
            </section>

%s
        </article>''' % (total, len(by_bp) - (1 if 'app' in by_bp else 0), '\n\n'.join(sections))


def main():
    docs = Path(sys.argv[1])
    tables = schema_sql()
    by_bp, total = routes()
    replace_article(docs / 'schema.html', build_schema(tables))
    replace_article(docs / 'routes.html', build_routes(by_bp, total))
    print('schema: %d tables; routes: %d across %d blueprints' % (len(tables), total, len(by_bp)))


if __name__ == '__main__':
    main()
